// <auto-generated />
using System;
using Loco.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loco.Infrastructure.Migrations
{
    [DbContext(typeof(LocoDbContext))]
    [Migration("20260209111404_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Loco.Domain.Fuel.Fuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("FinalFuel")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("InitialFuel")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("LocoId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Refueled")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocoId");

                    b.ToTable("Fuels");
                });

            modelBuilder.Entity("Loco.Domain.Locomotives.Locomotive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocomotiveType")
                        .HasColumnType("int");

                    b.Property<int>("MeasuringUnit")
                        .HasColumnType("int")
                        .HasComment(" Mh or Km");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Locomotives");
                });

            modelBuilder.Entity("Loco.Domain.Work.ShiftWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("FinalValue")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("InitialValue")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("LocoId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Shift")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocoId", "Date", "Shift")
                        .IsUnique()
                        .HasDatabaseName("IX_ShiftWork_Loco_Date_Shift");

                    b.ToTable("ShiftWorks");
                });

            modelBuilder.Entity("Loco.Domain.Fuel.Fuel", b =>
                {
                    b.HasOne("Loco.Domain.Locomotives.Locomotive", "Locomotive")
                        .WithMany("Fuels")
                        .HasForeignKey("LocoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Locomotive");
                });

            modelBuilder.Entity("Loco.Domain.Work.ShiftWork", b =>
                {
                    b.HasOne("Loco.Domain.Locomotives.Locomotive", "Locomotive")
                        .WithMany("ShiftWorks")
                        .HasForeignKey("LocoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Locomotive");
                });

            modelBuilder.Entity("Loco.Domain.Locomotives.Locomotive", b =>
                {
                    b.Navigation("Fuels");

                    b.Navigation("ShiftWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
